version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/Backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/Frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
