/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as authenticatedSidebarRouteRouteImport } from './routes/(authenticated)/_sidebar/route'
import { Route as authenticatedBooksReaderRouteRouteImport } from './routes/(authenticated)/books/reader/route'
import { Route as authenticatedSidebarStatusIndexRouteImport } from './routes/(authenticated)/_sidebar/status/index'
import { Route as authenticatedSidebarSeriesIndexRouteImport } from './routes/(authenticated)/_sidebar/series/index'
import { Route as authenticatedSidebarBooksIndexRouteImport } from './routes/(authenticated)/_sidebar/books/index'
import { Route as authenticatedSidebarAuthorsIndexRouteImport } from './routes/(authenticated)/_sidebar/authors/index'
import { Route as authenticatedBooksReaderBookIdRouteImport } from './routes/(authenticated)/books/reader/$bookId'
import { Route as authenticatedSidebarBooksSearchRouteImport } from './routes/(authenticated)/_sidebar/books/search'
import { Route as authenticatedSidebarBooksBookIdRouteImport } from './routes/(authenticated)/_sidebar/books/$bookId'
import { Route as authenticatedSidebarAuthorsSearchRouteImport } from './routes/(authenticated)/_sidebar/authors/search'
import { Route as authenticatedSidebarAuthorsAuthorIdRouteImport } from './routes/(authenticated)/_sidebar/authors/$authorId'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const authenticatedSidebarRouteRoute =
  authenticatedSidebarRouteRouteImport.update({
    id: '/_sidebar',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBooksReaderRouteRoute =
  authenticatedBooksReaderRouteRouteImport.update({
    id: '/books/reader',
    path: '/books/reader',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSidebarStatusIndexRoute =
  authenticatedSidebarStatusIndexRouteImport.update({
    id: '/status/',
    path: '/status/',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarSeriesIndexRoute =
  authenticatedSidebarSeriesIndexRouteImport.update({
    id: '/series/',
    path: '/series/',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarBooksIndexRoute =
  authenticatedSidebarBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarAuthorsIndexRoute =
  authenticatedSidebarAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedBooksReaderBookIdRoute =
  authenticatedBooksReaderBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => authenticatedBooksReaderRouteRoute,
  } as any)
const authenticatedSidebarBooksSearchRoute =
  authenticatedSidebarBooksSearchRouteImport.update({
    id: '/books/search',
    path: '/books/search',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarBooksBookIdRoute =
  authenticatedSidebarBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarAuthorsSearchRoute =
  authenticatedSidebarAuthorsSearchRouteImport.update({
    id: '/authors/search',
    path: '/authors/search',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)
const authenticatedSidebarAuthorsAuthorIdRoute =
  authenticatedSidebarAuthorsAuthorIdRouteImport.update({
    id: '/authors/$authorId',
    path: '/authors/$authorId',
    getParentRoute: () => authenticatedSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/books/reader': typeof authenticatedBooksReaderRouteRouteWithChildren
  '/authors/$authorId': typeof authenticatedSidebarAuthorsAuthorIdRoute
  '/authors/search': typeof authenticatedSidebarAuthorsSearchRoute
  '/books/$bookId': typeof authenticatedSidebarBooksBookIdRoute
  '/books/search': typeof authenticatedSidebarBooksSearchRoute
  '/books/reader/$bookId': typeof authenticatedBooksReaderBookIdRoute
  '/authors/': typeof authenticatedSidebarAuthorsIndexRoute
  '/books/': typeof authenticatedSidebarBooksIndexRoute
  '/series/': typeof authenticatedSidebarSeriesIndexRoute
  '/status/': typeof authenticatedSidebarStatusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/books/reader': typeof authenticatedBooksReaderRouteRouteWithChildren
  '/authors/$authorId': typeof authenticatedSidebarAuthorsAuthorIdRoute
  '/authors/search': typeof authenticatedSidebarAuthorsSearchRoute
  '/books/$bookId': typeof authenticatedSidebarBooksBookIdRoute
  '/books/search': typeof authenticatedSidebarBooksSearchRoute
  '/books/reader/$bookId': typeof authenticatedBooksReaderBookIdRoute
  '/authors': typeof authenticatedSidebarAuthorsIndexRoute
  '/books': typeof authenticatedSidebarBooksIndexRoute
  '/series': typeof authenticatedSidebarSeriesIndexRoute
  '/status': typeof authenticatedSidebarStatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(authenticated)/_sidebar': typeof authenticatedSidebarRouteRouteWithChildren
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(authenticated)/books/reader': typeof authenticatedBooksReaderRouteRouteWithChildren
  '/(authenticated)/_sidebar/authors/$authorId': typeof authenticatedSidebarAuthorsAuthorIdRoute
  '/(authenticated)/_sidebar/authors/search': typeof authenticatedSidebarAuthorsSearchRoute
  '/(authenticated)/_sidebar/books/$bookId': typeof authenticatedSidebarBooksBookIdRoute
  '/(authenticated)/_sidebar/books/search': typeof authenticatedSidebarBooksSearchRoute
  '/(authenticated)/books/reader/$bookId': typeof authenticatedBooksReaderBookIdRoute
  '/(authenticated)/_sidebar/authors/': typeof authenticatedSidebarAuthorsIndexRoute
  '/(authenticated)/_sidebar/books/': typeof authenticatedSidebarBooksIndexRoute
  '/(authenticated)/_sidebar/series/': typeof authenticatedSidebarSeriesIndexRoute
  '/(authenticated)/_sidebar/status/': typeof authenticatedSidebarStatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/books/reader'
    | '/authors/$authorId'
    | '/authors/search'
    | '/books/$bookId'
    | '/books/search'
    | '/books/reader/$bookId'
    | '/authors/'
    | '/books/'
    | '/series/'
    | '/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/books/reader'
    | '/authors/$authorId'
    | '/authors/search'
    | '/books/$bookId'
    | '/books/search'
    | '/books/reader/$bookId'
    | '/authors'
    | '/books'
    | '/series'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(unauthenticated)'
    | '/(authenticated)/_sidebar'
    | '/(unauthenticated)/login'
    | '/(authenticated)/books/reader'
    | '/(authenticated)/_sidebar/authors/$authorId'
    | '/(authenticated)/_sidebar/authors/search'
    | '/(authenticated)/_sidebar/books/$bookId'
    | '/(authenticated)/_sidebar/books/search'
    | '/(authenticated)/books/reader/$bookId'
    | '/(authenticated)/_sidebar/authors/'
    | '/(authenticated)/_sidebar/books/'
    | '/(authenticated)/_sidebar/series/'
    | '/(authenticated)/_sidebar/status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenticated)/_sidebar': {
      id: '/(authenticated)/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedSidebarRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/books/reader': {
      id: '/(authenticated)/books/reader'
      path: '/books/reader'
      fullPath: '/books/reader'
      preLoaderRoute: typeof authenticatedBooksReaderRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/_sidebar/status/': {
      id: '/(authenticated)/_sidebar/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof authenticatedSidebarStatusIndexRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/series/': {
      id: '/(authenticated)/_sidebar/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof authenticatedSidebarSeriesIndexRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/books/': {
      id: '/(authenticated)/_sidebar/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof authenticatedSidebarBooksIndexRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/authors/': {
      id: '/(authenticated)/_sidebar/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof authenticatedSidebarAuthorsIndexRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/books/reader/$bookId': {
      id: '/(authenticated)/books/reader/$bookId'
      path: '/$bookId'
      fullPath: '/books/reader/$bookId'
      preLoaderRoute: typeof authenticatedBooksReaderBookIdRouteImport
      parentRoute: typeof authenticatedBooksReaderRouteRoute
    }
    '/(authenticated)/_sidebar/books/search': {
      id: '/(authenticated)/_sidebar/books/search'
      path: '/books/search'
      fullPath: '/books/search'
      preLoaderRoute: typeof authenticatedSidebarBooksSearchRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/books/$bookId': {
      id: '/(authenticated)/_sidebar/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof authenticatedSidebarBooksBookIdRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/authors/search': {
      id: '/(authenticated)/_sidebar/authors/search'
      path: '/authors/search'
      fullPath: '/authors/search'
      preLoaderRoute: typeof authenticatedSidebarAuthorsSearchRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
    '/(authenticated)/_sidebar/authors/$authorId': {
      id: '/(authenticated)/_sidebar/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof authenticatedSidebarAuthorsAuthorIdRouteImport
      parentRoute: typeof authenticatedSidebarRouteRoute
    }
  }
}

interface authenticatedSidebarRouteRouteChildren {
  authenticatedSidebarAuthorsAuthorIdRoute: typeof authenticatedSidebarAuthorsAuthorIdRoute
  authenticatedSidebarAuthorsSearchRoute: typeof authenticatedSidebarAuthorsSearchRoute
  authenticatedSidebarBooksBookIdRoute: typeof authenticatedSidebarBooksBookIdRoute
  authenticatedSidebarBooksSearchRoute: typeof authenticatedSidebarBooksSearchRoute
  authenticatedSidebarAuthorsIndexRoute: typeof authenticatedSidebarAuthorsIndexRoute
  authenticatedSidebarBooksIndexRoute: typeof authenticatedSidebarBooksIndexRoute
  authenticatedSidebarSeriesIndexRoute: typeof authenticatedSidebarSeriesIndexRoute
  authenticatedSidebarStatusIndexRoute: typeof authenticatedSidebarStatusIndexRoute
}

const authenticatedSidebarRouteRouteChildren: authenticatedSidebarRouteRouteChildren =
  {
    authenticatedSidebarAuthorsAuthorIdRoute:
      authenticatedSidebarAuthorsAuthorIdRoute,
    authenticatedSidebarAuthorsSearchRoute:
      authenticatedSidebarAuthorsSearchRoute,
    authenticatedSidebarBooksBookIdRoute: authenticatedSidebarBooksBookIdRoute,
    authenticatedSidebarBooksSearchRoute: authenticatedSidebarBooksSearchRoute,
    authenticatedSidebarAuthorsIndexRoute:
      authenticatedSidebarAuthorsIndexRoute,
    authenticatedSidebarBooksIndexRoute: authenticatedSidebarBooksIndexRoute,
    authenticatedSidebarSeriesIndexRoute: authenticatedSidebarSeriesIndexRoute,
    authenticatedSidebarStatusIndexRoute: authenticatedSidebarStatusIndexRoute,
  }

const authenticatedSidebarRouteRouteWithChildren =
  authenticatedSidebarRouteRoute._addFileChildren(
    authenticatedSidebarRouteRouteChildren,
  )

interface authenticatedBooksReaderRouteRouteChildren {
  authenticatedBooksReaderBookIdRoute: typeof authenticatedBooksReaderBookIdRoute
}

const authenticatedBooksReaderRouteRouteChildren: authenticatedBooksReaderRouteRouteChildren =
  {
    authenticatedBooksReaderBookIdRoute: authenticatedBooksReaderBookIdRoute,
  }

const authenticatedBooksReaderRouteRouteWithChildren =
  authenticatedBooksReaderRouteRoute._addFileChildren(
    authenticatedBooksReaderRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedSidebarRouteRoute: typeof authenticatedSidebarRouteRouteWithChildren
  authenticatedBooksReaderRouteRoute: typeof authenticatedBooksReaderRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedSidebarRouteRoute: authenticatedSidebarRouteRouteWithChildren,
  authenticatedBooksReaderRouteRoute:
    authenticatedBooksReaderRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
