/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as authenticatedStatusIndexRouteImport } from './routes/(authenticated)/status/index'
import { Route as authenticatedSeriesIndexRouteImport } from './routes/(authenticated)/series/index'
import { Route as authenticatedBooksIndexRouteImport } from './routes/(authenticated)/books/index'
import { Route as authenticatedAuthorsIndexRouteImport } from './routes/(authenticated)/authors/index'
import { Route as authenticatedBooksSearchRouteImport } from './routes/(authenticated)/books/search'
import { Route as authenticatedAuthorsSearchRouteImport } from './routes/(authenticated)/authors/search'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const authenticatedStatusIndexRoute =
  authenticatedStatusIndexRouteImport.update({
    id: '/status/',
    path: '/status/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSeriesIndexRoute =
  authenticatedSeriesIndexRouteImport.update({
    id: '/series/',
    path: '/series/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBooksIndexRoute = authenticatedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedAuthorsIndexRoute =
  authenticatedAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBooksSearchRoute =
  authenticatedBooksSearchRouteImport.update({
    id: '/books/search',
    path: '/books/search',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAuthorsSearchRoute =
  authenticatedAuthorsSearchRouteImport.update({
    id: '/authors/search',
    path: '/authors/search',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/authors/search': typeof authenticatedAuthorsSearchRoute
  '/books/search': typeof authenticatedBooksSearchRoute
  '/authors/': typeof authenticatedAuthorsIndexRoute
  '/books/': typeof authenticatedBooksIndexRoute
  '/series/': typeof authenticatedSeriesIndexRoute
  '/status/': typeof authenticatedStatusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/authors/search': typeof authenticatedAuthorsSearchRoute
  '/books/search': typeof authenticatedBooksSearchRoute
  '/authors': typeof authenticatedAuthorsIndexRoute
  '/books': typeof authenticatedBooksIndexRoute
  '/series': typeof authenticatedSeriesIndexRoute
  '/status': typeof authenticatedStatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(authenticated)/authors/search': typeof authenticatedAuthorsSearchRoute
  '/(authenticated)/books/search': typeof authenticatedBooksSearchRoute
  '/(authenticated)/authors/': typeof authenticatedAuthorsIndexRoute
  '/(authenticated)/books/': typeof authenticatedBooksIndexRoute
  '/(authenticated)/series/': typeof authenticatedSeriesIndexRoute
  '/(authenticated)/status/': typeof authenticatedStatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/authors/search'
    | '/books/search'
    | '/authors/'
    | '/books/'
    | '/series/'
    | '/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/authors/search'
    | '/books/search'
    | '/authors'
    | '/books'
    | '/series'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(unauthenticated)'
    | '/(unauthenticated)/login'
    | '/(authenticated)/authors/search'
    | '/(authenticated)/books/search'
    | '/(authenticated)/authors/'
    | '/(authenticated)/books/'
    | '/(authenticated)/series/'
    | '/(authenticated)/status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenticated)/status/': {
      id: '/(authenticated)/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof authenticatedStatusIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/series/': {
      id: '/(authenticated)/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof authenticatedSeriesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/books/': {
      id: '/(authenticated)/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof authenticatedBooksIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/authors/': {
      id: '/(authenticated)/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof authenticatedAuthorsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/books/search': {
      id: '/(authenticated)/books/search'
      path: '/books/search'
      fullPath: '/books/search'
      preLoaderRoute: typeof authenticatedBooksSearchRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/authors/search': {
      id: '/(authenticated)/authors/search'
      path: '/authors/search'
      fullPath: '/authors/search'
      preLoaderRoute: typeof authenticatedAuthorsSearchRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedAuthorsSearchRoute: typeof authenticatedAuthorsSearchRoute
  authenticatedBooksSearchRoute: typeof authenticatedBooksSearchRoute
  authenticatedAuthorsIndexRoute: typeof authenticatedAuthorsIndexRoute
  authenticatedBooksIndexRoute: typeof authenticatedBooksIndexRoute
  authenticatedSeriesIndexRoute: typeof authenticatedSeriesIndexRoute
  authenticatedStatusIndexRoute: typeof authenticatedStatusIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedAuthorsSearchRoute: authenticatedAuthorsSearchRoute,
  authenticatedBooksSearchRoute: authenticatedBooksSearchRoute,
  authenticatedAuthorsIndexRoute: authenticatedAuthorsIndexRoute,
  authenticatedBooksIndexRoute: authenticatedBooksIndexRoute,
  authenticatedSeriesIndexRoute: authenticatedSeriesIndexRoute,
  authenticatedStatusIndexRoute: authenticatedStatusIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
