spring:
  application:
    name: backend
  thread:
    virtual:
      enabled: true
  flyway:
      locations: classpath:db/migration
      baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
server:
  port: 8000
management:
  endpoints:
    web:
      base-path: /api/actuator
media-sanctum:
  config-dir: ${CONFIG}
  data-dir: ${DATA}
  cookies-secure: true
  log-stack-traces: false
  jwt:
    secret: ${JWT_SECRET}
    access-exp:
      time-unit: HOURS
      value: 1
    refresh-exp:
      time-unit: DAYS
      value: 30
  log:
    path: ${CONFIG}/logs/media-sanctum.jsonl
  db:
    pool-size: 5
    connection-timeout-ms: 30_000
    busy-timeout-ms: 30_000
  hardcover:
    api-key: ${HARDCOVER_API_KEY}
    endpoint: https://api.hardcover.app/v1/graphql

resilience4j:
  ratelimiter:
    instances:
      hardcover:
        limit-for-period: 1
        limit-refresh-period: 1s
        timeout-duration: 1s
  retry:
    instances:
      hardcover:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
